baseURL = "/"
# title = "Hugo Themes"
author = "Oleh Andrushko"
copyright = "Copyright © 2021 Oleh Andrushko"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "hugo-paper"
title = "Hogo Example Site"

[params] 
  github = 'olich97'
# ------------------------------

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = true
    simple = true

  [privacy.twitter]
    disabled = true
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = true
    simple = true

  [privacy.youtube]
    disabled = true
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
